-- 7 - OUR FIRST DATABASE
CREATE DATABASE CH_37;
USE CH_37;

-- 8 - OUR FIRST TABLE
CREATE TABLE STUDENT(
	roll INT,
	name VARCHAR(30),
    age INT
);

INSERT INTO STUDENT VALUES
(66, 'SOMESH GAIKWAD', 21),
(67, 'GAURAV PAWAR', 20),
(68, 'PRATIK NIKAM', 21);

SELECT *FROM STUDENT;

-- 9 - DATABASE QUERIES

SHOW DATABASES;
SHOW TABLES;

-- 11 - WHAT ARE CONSTRAINTS

CREATE TABLE TABLE_11_12(
	id INT UNIQUE,
    age INT,
    name VARCHAR(30) NOT NULL,
    followers INT DEFAULT 0,
    following INT DEFAULT 0,
    CONSTRAINT age_check CHECK (age >= 18),
    PRIMARY KEY (id)
);

CREATE TABLE TABLE_12(
	id INT PRIMARY KEY,
    content VARCHAR(100),
    user_id INT,
    FOREIGN KEY (user_id) REFERENCES TABLE_11_12(id)
);

-- 14 - INSERT INTO TABLE

INSERT INTO TABLE_11_12 
(id, age, name, followers, following)
VALUES 
(66, 20, 'SOMESH GAIKWAD', 1200, 10),
(67, 21, 'GAURAV PAWAR', 150, 100),
(68, 22, 'PRATIK NIKAM', 1500, 10),
(69, 20, 'ADITYA SADAMARE', 140, 1000),
(70, 23, 'SHIVRAM PAWAR', 70, 180);

INSERT INTO TABLE_12
(id, content, user_id)
VALUES
(1, 'HOW I CRACKED MICROSOFT IN 1ST ATTEMPT', 67),
(2, 'MY FIRST ISRO INTERNSHIP EXPERIENCE', 68),
(3, 'YOU CANT SEE ME', 69);

-- 15 - SELECT COMMAND

SELECT * FROM TABLE_11_12;
SELECT id, name FROM TABLE_11_12; 

SELECT * FROM TABLE_12;